name: Build

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build-pghstatic:
    name: Build PghStatic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"

      - name: Build JAR
        run: |
          ./gradlew build

      - name: Upload to GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          gh release upload "${{ github.event.release.tag_name }}" build/libs/*